// <auto-generated />
using System;
using BoilerPlate.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoilerPlate.Migrations
{
    [DbContext(typeof(BoilerPlateDbContext))]
    partial class BoilerPlateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoilerPlate.Models.Kancelarija", b =>
                {
                    b.Property<long>("KancelarijaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Opis");

                    b.HasKey("KancelarijaId");

                    b.ToTable("Kancelarije");
                });

            modelBuilder.Entity("BoilerPlate.Models.Osoba", b =>
                {
                    b.Property<long>("OsobaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime");

                    b.Property<long>("KancelarijaId");

                    b.Property<string>("Prezime");

                    b.HasKey("OsobaId");

                    b.HasIndex("KancelarijaId");

                    b.ToTable("Osobe");
                });

            modelBuilder.Entity("BoilerPlate.Models.OsobaUredjaj", b =>
                {
                    b.Property<long>("OsobaUredjajId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("OsobaId");

                    b.Property<long>("UredjajId");

                    b.Property<DateTime?>("VrijemeDo");

                    b.Property<DateTime>("VrijemeOd");

                    b.HasKey("OsobaUredjajId");

                    b.HasIndex("OsobaId");

                    b.HasIndex("UredjajId");

                    b.ToTable("OsobeUredjaji");
                });

            modelBuilder.Entity("BoilerPlate.Models.Uredjaj", b =>
                {
                    b.Property<long>("UredjajId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("OsobaId");

                    b.Property<string>("UredjajIme");

                    b.HasKey("UredjajId");

                    b.HasIndex("OsobaId");

                    b.ToTable("Uredjaji");
                });

            modelBuilder.Entity("BoilerPlate.Models.Osoba", b =>
                {
                    b.HasOne("BoilerPlate.Models.Kancelarija", "Kancelarija")
                        .WithMany("ListaOsobe")
                        .HasForeignKey("KancelarijaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoilerPlate.Models.OsobaUredjaj", b =>
                {
                    b.HasOne("BoilerPlate.Models.Osoba", "Osoba")
                        .WithMany("ListaKoriscenje")
                        .HasForeignKey("OsobaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BoilerPlate.Models.Uredjaj", "Uredjaj")
                        .WithMany("ListaKoriscenje")
                        .HasForeignKey("UredjajId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoilerPlate.Models.Uredjaj", b =>
                {
                    b.HasOne("BoilerPlate.Models.Osoba", "Osoba")
                        .WithMany("ListaUredjaji")
                        .HasForeignKey("OsobaId");
                });
#pragma warning restore 612, 618
        }
    }
}
